In [1]:
try:
    spark.stop()
except Exception as e:
    pass

# ⚙️ 1. Setup Spark local (avec support Delta)

In [2]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import col

spark = (
    SparkSession.builder
    .appName("RecipeSearchPoC")
    # Support Delta Lake
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    # Broadcast join automatique pour df_index (table d'index souvent < 200 Mo)
    .config("spark.sql.autoBroadcastJoinThreshold", "200m")
    # Gestion de la mémoire occupée par Spark
    .config("spark.executor.memory", "3g")  # Mémoire allouée à chaque nœud de calcul
    .config("spark.driver.memory", "1g")    # Mémoire allouée au chef d'orchestre
    .getOrCreate()
)

print("✅ Spark ready")

✅ Spark ready

# 📥 2. Chargement des données

In [3]:
DATA_PATH = "../data/recipes_parquets"

# Delta gère nativement le Data Skipping et le Z-Order définis dans le pipeline
df_main      = spark.read.format("delta").load(f"{DATA_PATH}/recipes_main")
df_index     = spark.read.format("delta").load(f"{DATA_PATH}/ingredients_index").cache()
df_nutrition = spark.read.format("delta").load(f"{DATA_PATH}/recipes_nutrition_detail")

df_index.count()

print("Table 'df_index' mise en cache")

26/04/08 18:45:31 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

Table 'df_index' mise en cache

# 🔗 3. Vue master

In [4]:
# On définit le join une seule fois — Spark ne l'exécute qu'à la demande
df_master = df_main.join(df_nutrition, on="recipe_id", how="left")

print(f"Colonnes master ({len(df_master.columns)}) : {df_master.columns}")

Colonnes master (22) : ['recipe_id', 'title', 'description', 'instructions_text', 'ingredients_raw', 'ingredients_validated', 'n_ingredients_validated', 'n_steps', 'cook_minutes', 'cook_time_category', 'image_url', 'image_urls', 'has_image', 'source_url', 'energy_kcal', 'nutri_score', 'tags', 'fat_g', 'protein_g', 'salt_g', 'saturates_g', 'sugars_g']

# 🔎 4. Recherche par nom

In [5]:
def search_by_name(query: str, limit: int = 20) -> list[dict]:
    rows = (
        df_main
        .filter(col("title").ilike(f"%{query}%"))
        .select("recipe_id", "title", "cook_minutes", "nutri_score", "image_url")
        .limit(limit)
        .collect()
    )
    return [r.asDict() for r in rows]

# Test
search_by_name("pasta")

[{'recipe_id': 'c7372c374e',
  'title': 'Homemade Fettuccini Pasta Dough',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://s-media-cache-ak0.pinimg.com/736x/92/40/ff/9240ffe585bacb3addf8a3a26ba5ccdc.jpg'},
 {'recipe_id': 'e53039454b',
  'title': 'Egyptian Koshary Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://thumbs.dreamstime.com/z/egyptian-food-koshary-pasta-sauce-traditional-made-spaghetti-chickpeas-rice-onion-74514441.jpg'},
 {'recipe_id': '7b22c46b8e',
  'title': 'Greek Orzo Pasta Salad',
  'cook_minutes': 20,
  'nutri_score': 'E',
  'image_url': 'http://www.hummusapien.com/wp-content/uploads/2013/09/greeksalad21.jpg'},
 {'recipe_id': '309ca5c971',
  'title': 'Cucumber Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://cdn.skim.gs/image/upload/c_fill,dpr_1.0,f_auto,fl_lossy,q_auto,w_940/v1456344637/msi/cucumber_noodles_3_ayjyye.jpg'},
 {'recipe_id': '27085e38d7',
  'title': 'Crabstick pasta salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://img-global.cpcdn.com/001_recipes/5839769624903680/0x0/photo.jpg'},
 {'recipe_id': '0e90bd4380',
  'title': 'Hearty Whole Wheat Pasta With Brussels Sprouts, Cheese and Potato',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://graphics8.nytimes.com/images/2013/03/04/dining/video-recipelab-nigella-031513/video-recipelab-nigella-031513-superJumbo-v2.jpg'},
 {'recipe_id': '4a08b98086',
  'title': 'Garlic Chickpea Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://tastykitchen.com/recipes/wp-content/uploads/sites/2/2011/02/5469857366_75b4a2f62c_z-410x273.jpg'},
 {'recipe_id': '2fef790bbc',
  'title': 'Greek Pasta Recipe',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://www.hy-vee.com/webres/Image/Recipes/Greek-Pasta-with-Shrimp-Garbanzo-Beans-and-Lemon.jpg'},
 {'recipe_id': 'ba6e749d43',
  'title': 'Creamy Southwestern BBQ Pasta Salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://resources.salewhale.ca/brand_lists_images/2/recipes/B/0/9/9A07/creamy-southwestern-bbq-pasta-salad.jpeg'},
 {'recipe_id': '1b97c3a5a8',
  'title': 'Creamy Three Cheese Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://www.recipe-diaries.com/wp-content/uploads/2015/04/one-pot-creamy-pasta-016.jpg'},
 {'recipe_id': 'b696b27689',
  'title': 'Greek Medley Pasta Salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://s-media-cache-ak0.pinimg.com/236x/57/d2/8c/57d28cbe93831655d0c6fc588c10180a--rainbow-pasta-vegetable-medley.jpg'},
 {'recipe_id': '6d21b5fadb',
  'title': 'Creamy Garlic And Herb Veggie Pasta Pot',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://img-global.cpcdn.com/001_recipes/4854372027072512/0x0/photo.jpg'},
 {'recipe_id': '355d811e99',
  'title': 'Creamy Asparagus Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://lovingitvegan.com/wp-content/uploads/2016/07/Creamy-Asparagus-Pasta-11.jpg'},
 {'recipe_id': 'f877648c04',
  'title': 'Heirloom Tomato Herb Pasta Salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://img07.foodily.net/img/620x620/60dd8b78c4f6.jpg'},
 {'recipe_id': '4227b82ff1',
  'title': 'Cold Pasta Primavera Salad from Hidden Valley',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://images.media-allrecipes.com/userphotos/250x250/3557338.jpg'},
 {'recipe_id': '61a2de4a5b',
  'title': 'Creamy Pasta and Sausage',
  'cook_minutes': 50,
  'nutri_score': 'E',
  'image_url': 'http://2.bp.blogspot.com/_7DIav3PovY0/TEehVWcvhII/AAAAAAAABGI/4kKQe5867-0/s1600/IMG_3791.JPG'},
 {'recipe_id': '23e23f762a',
  'title': 'Fresh Light Whole Wheat Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://recipeland.com/images/r/3141/1c9ec7f8e2e2a36a0601_550.jpg'},
 {'recipe_id': '50e0f42018',
  'title': 'Curry Pasta Salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://images.media-allrecipes.com/userphotos/256x256/28940.jpg'},
 {'recipe_id': '4895176bfe',
  'title': 'Creamy Chicken and Pasta Salad',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'https://thefrostingonthecakes.files.wordpress.com/2011/10/photo_0d3e5f5f-4290-0752-6b5c-e0bf2abd0b76.jpg'},
 {'recipe_id': '8627cc8e83',
  'title': 'Easy Smoked Salmon Pasta',
  'cook_minutes': None,
  'nutri_score': 'E',
  'image_url': 'http://www.theendlessmeal.com/wp-content/uploads/2014/05/easy-pasta-600-3.jpg'}]

# 🥕 5. Recherche par ingrédient (le cœur)

In [6]:
def search_by_ingredient(ingredient):
    """
    df_index est typiquement < 200 Mo → AQE le broadcast automatiquement.
    Le join devient un map-side join, pas de shuffle sur df_master.
    """
    recipe_ids = (
        df_index
        .filter(col("ingredient").ilike(f"%{ingredient}%"))
        .select("recipe_id")
        .distinct()
    )
    return (
        df_master
        .join(recipe_ids, on="recipe_id")
        .select("recipe_id", "title", "cook_minutes", "nutri_score", "image_url", "ingredients_raw")
        .limit(20)
    )

# Test
search_by_ingredient("tomato").toPandas()

,recipe_id,title,cook_minutes,nutri_score,image_url,ingredients_raw
0,376b1b0634,Green Tomato Chutney Dog,NaN,E,http://www.fnstatic.co.uk/images/small/package...,"[1 1/2 pounds green tomatoes, diced, 3 green a..."
1,6a6a067abc,Easy Chicken Tortilla Soup,40.0,E,http://dailydietitian.com/blog/wp-content/uplo...,"[2 (14 1/2 ounce) cans diced tomatoes, 3 cups ..."
2,303e4c111d,"Family-Size Tomato, Bacon and Garlic Omelet",NaN,E,https://eatatelmers.com/wp-content/uploads/201...,"[8 large eggs, salt and pepper, 8 slices bacon..."
3,fec137147a,Healthy Black Bean Chicken,35.0,E,http://1.bp.blogspot.com/_60dqOZb_22w/TUyzgck4...,"[2 -4 boneless skinless chicken breasts, 2 tea..."
4,c2d81a6e7a,Easy Chicken Dinner,NaN,E,http://cdn-jpg.allyou.com/sites/default/files/...,[4 small boneless skinless chicken breasts (1 ...
5,c9e52d8c89,Green Devil Cake and Chocolate Glaze,NaN,E,https://pinchstatic.global.ssl.fastly.net/reci...,"[2 1/2 cups flour, all-purpose, 1 3/4 cups bro..."
6,cd543c1d97,Grilled Mahimahi and Green Tomatoes,NaN,E,https://scrappycat.smugmug.com/Food/Cooking-20...,"[1 1/2 pounds firm green tomatoes, sliced cros..."
7,6a19eefafe,Crispy Topped Roasted Tomatoe Wedges,NaN,E,https://img-global.cpcdn.com/001_recipes/61655...,"[2 large red ripe firm fresh tomatoes, 1 tbsp ..."
8,53bf7f9ed4,Grilled Mediterranean Greek Pizza with Sundrie...,NaN,E,http://images.media-allrecipes.com/userphotos/...,[1 (12 ounce) package al fresco All Natural Su...
9,1c29158510,Grilled Pepper Poppers,NaN,E,http://www.eat-drink-smile.com/wp-content/uplo...,"[1/2 cup (4 ounces) soft goat cheese, 1/2 cup ..."
10,1dee1bf770,Grilled Tuna with Grilled Asparagus and Oven R...,NaN,E,https://s-media-cache-ak0.pinimg.com/736x/9a/2...,"[6 (5-ounce) portions yellowfin tuna, 1 teaspo..."
11,559f3459f8,Fried Tomatoes with Mint Couscous,NaN,E,https://recipeland.com/images/r/5678/082359a4c...,[1 1/4 cups vegetable stock brought to the boi...
12,e1641acc34,Hearty Meat Lasagna (Oamc),NaN,E,https://s-media-cache-ak0.pinimg.com/236x/88/4...,"[2 tablespoons olive oil, 1 medium onion, minc..."
13,f3c589f33f,Ground Beef & Cabbage Casserole,NaN,E,http://2.bp.blogspot.com/-DS6CtAE_Xlo/UBX-Lsgp...,"[2 12 lbs ground beef, cooked and drained, 1 m..."
14,9e50274e27,Coconut Red Lentil Soup,NaN,E,http://tastykitchen.com/recipes/wp-content/upl...,"[1 Tablespoon Olive Oil, 1 Tablespoon Curry Po..."
15,91f1ca1276,Farm-Fresh Quesadillas,NaN,E,http://assets.kraftfoods.com/recipe_images/ope...,"[1 zucchini, sliced, 1 tomato, chopped, 2 whol..."
16,5f599e69b2,Ham and Cheese Toasted Sandwich,NaN,E,https://thumb9.shutterstock.com/display_pic_wi...,"[1/4 cup (2 ounces) tub light cream cheese, 1 ..."
17,ebef9210fd,Chucky Salsa,NaN,E,https://img-global.cpcdn.com/001_recipes/56510...,"[3 medium tomatoes, 1 large onion, 1 red bell ..."
18,c7487c1375,Horiatiki (Greek Villagers Salad),NaN,E,"http://img.sndimg.com/food/image/upload/w_512,...","[3 large firm tomatoes, 1 large red onion, pee..."
19,dba14b9780,Dried Lima Beans Soup Recipe,NaN,E,https://s-media-cache-ak0.pinimg.com/736x/46/8...,"[1 pound dry lima beans, 1 ham bone, 2 cans ch..."

# 🧠 6. Recherche avancée (clé du PoC)

In [7]:
def search_advanced(name=None, ingredient=None, max_time=None, nutri_score=None):
    """
    Les filtres sont poussés avant le join (predicate pushdown).
    Spark n'ouvre que les fichiers Delta concernés.
    """
    df = df_master

    if name:
        df = df.filter(col("title").ilike(f"%{name}%"))

    if max_time:
        df = df.filter(col("cook_minutes") <= max_time)

    if nutri_score:
        df = df.filter(col("nutri_score") == nutri_score)

    # Le join sur df_index vient EN DERNIER pour profiter des filtres précédents
    if ingredient:
        recipe_ids = (
            df_index
            .filter(col("ingredient").ilike(f"%{ingredient}%"))
            .select("recipe_id")
            .distinct()
        )
        df = df.join(recipe_ids, on="recipe_id")

    return df.select(
        "recipe_id",
        "title",
        "cook_minutes",
        "cook_time_category",
        "nutri_score",
        "energy_kcal",
        "image_url",
        "ingredients_raw",
    ).limit(20)

# Test : recettes rapides avec nutri_score A
search_advanced(max_time=30, nutri_score="A").toPandas()

,recipe_id,title,cook_minutes,cook_time_category,nutri_score,energy_kcal,image_url,ingredients_raw
0,22e5882cfb,Better Frizzled Cabbage,20,rapide,A,46.700001,http://www.annsentitledlife.com/wp-content/upl...,"[1 (16 ounce) bag coleslaw mix, 2 slices bacon..."
1,0ad9232f41,Marinade for Steak,15,rapide,A,46.500000,"http://img.sndimg.com/food/image/upload/w_512,...","[1 tablespoon olive oil, 2 tablespoons soy sau..."
2,fae646ea12,Strawberry Blender Blast,5,rapide,A,53.701080,http://2.bp.blogspot.com/-IM-LgvwuZzU/Un83kHMA...,"[1 12 cups fresh halved strawberries, 12 cup s..."
3,b15859ee59,No Sugar Fruit Cookies,25,rapide,A,57.400002,http://www.fashionfoodmusic.com/wp-content/upl...,"[1 cup chopped dates, 12 cup finely chopped pe..."
4,e08c4f00dc,Butterbeer,2,rapide,A,45.483196,"http://img.sndimg.com/food/image/upload/w_512,...","[1 cup brown sugar, 4 tablespoons butter, 12 t..."
5,d42d98bb81,Steamed Broccoli,3,rapide,A,34.000000,"http://img.sndimg.com/food/image/upload/w_512,...","[1 12 lbs broccoli, salt and pepper, 3 tablesp..."
6,bcbae7110a,Spicy Zucchini,10,rapide,A,57.099998,http://neighborfoodblog.com/wp-content/uploads...,"[1 lb zucchini, 3 tablespoons olive oil, 2 ear..."
7,93f9cf59df,Cajun Tuna Spread,5,rapide,A,62.400002,https://www.weightwatchers.com/images/1033/dyn...,"[13 cup cream cheese, softened, 3 tablespoons ..."
8,747f6d0de1,Mango Lassi Smoothie,10,rapide,A,53.941128,https://silkroutechef.files.wordpress.com/2013...,"[1 ripe mango, 12 cup vanilla yogurt, 14 cup 1..."
9,7660ce921b,Quick Homemade Tomato Soup,17,rapide,A,79.099998,"http://img.sndimg.com/food/image/upload/w_512,...","[2 tablespoons butter, 2 tablespoons olive oil..."
10,a4776070c7,Cucumbers in Vinegar,5,rapide,A,11.320755,"http://img.sndimg.com/food/image/upload/w_512,...","[12 cup cucumber, sliced in bite sized pieces ..."
11,abf0aafd87,Seasoned Breadcrumbs,20,rapide,A,72.699997,http://omgfood.com/wp-content/uploads/2015/07/...,[4 cups plain breadcrumbs (about 12 slices of ...
12,78d42edde4,Chilled Moroccan Tomato Soup,20,rapide,A,74.699997,http://img1.sunset.timeinc.net/sites/default/f...,"[2 medium tomatoes, diced, 1 stalk celery, min..."
13,cd6711ba0d,Satay,30,rapide,A,52.013027,"http://img.sndimg.com/food/image/upload/w_512,...","[1 teaspoon sugar, 1 teaspoon salt, 1 lb pork,..."
14,52ee50ffd9,Green Goddess,5,rapide,A,1.600000,http://cdn.images.express.co.uk/img/dynamic/20...,"[1 teaspoon lemon juice, 12 bottle lemonade (c..."
15,f3bc21ce3a,Heirloom Tomato Salad,10,rapide,A,50.421482,https://www.littlebroken.com/wp-content/upload...,"[1 cup baby arugula, washed, 1/4 cup high-qual..."
16,7bce90142c,Low Carb Barbecue Sauce,25,rapide,A,17.700001,http://www.poormansatkins.com/uploads/6/1/7/0/...,"[1 cup low-carb ketchup, 2 teaspoons Worcester..."
17,78be7744c9,Beet and Horseradish Relish,5,rapide,A,45.725342,https://www.thebaytree.co.uk/_uploads/baytree....,"[10 cups cooked beets, grated, 2 cups horserad..."
18,185ebe3ab9,Stir Fried Broccoli With Orange and Ginger,18,rapide,A,67.800003,"http://img.sndimg.com/food/image/upload/w_512,...","[500 g broccoli, 12 tablespoon peanut oil, 2 t..."
19,dda9acd0aa,Fruit Smoothie,10,rapide,A,43.198650,http://assets.kraftfoods.com/recipe_images/ope...,"[2 cups vanilla low-fat yogurt, 1 pkg. (10 oz...."

# 🍽️ 7. Affichage recette complète

In [8]:
def show_recipe(recipe_id):
    """
    .limit(1).collect() = Spark s'arrête dès le 1er match,
    pas de scan complet de la table.
    """
    recipe = (
        df_master
        .filter(col("recipe_id") == recipe_id)
        .limit(1)
        .collect()
    )

    if not recipe:
        print("❌ Recette introuvable")
        return

    r = recipe[0].asDict()

    print("🍽️ ", r.get("title", "—"))
    print("⏱️  Temps      :", r.get("cook_minutes"), "min  [", r.get("cook_time_category"), "]")
    print("🔥 Calories   :", r.get("energy_kcal"), "kcal")
    print("🥗 Nutri-score:", r.get("nutri_score"))
    print("🖼️  Image      :", r.get("image_url"))
    print("\n📝 Ingrédients:")
    print(r.get("ingredients_raw", "—"))
    print("\n👨‍🍳 Instructions:")
    print(r.get("instructions_text", "—"))

# Test : 1er recipe_id disponible
first_id = df_main.select("recipe_id").first()["recipe_id"]
show_recipe(first_id)

🍽️  Pumpkin Creme Caramel
⏱️  Temps      : 65 min  [ long ]
🔥 Calories   : 247.10000610351562 kcal
🥗 Nutri-score: C
🖼️  Image      : http://recipegreat.com/images/pumpkin-creme-caramel-02.jpg

📝 Ingrédients:
['23 cup plus 1/2 cup sugar, divided', '1/2 tsp. salt, divided', '4 large eggs', '1 1/4 cups pumpkin puree or pure canned pumpkin', '2 tsp. vanilla extract', '1/2 tsp. plus 18 tsp. pumpkin pie spice', '1 12-oz. can low-fat evaporated milk', '1/2 cup whole milk']

👨‍🍳 Instructions:
Preheat oven to 350F. | Lightly coat 8 6-oz. | ramekins with cooking spray, and set in 2-inch-deep baking pan. | Combine 2/3 cup sugar, 1/4 tsp. | salt, and 1 Tbs. | water in small saucepan, and bring to a boil over medium heat. | Cook 8 to 10 minutes without stirring, or until edges start to color. | Swirl pan gently to distribute browned sugar; continue to cook 1 to 2 minutes more, or until sugar is deep golden brown. | Pour 1 Tbs. | caramelized sugar into each ramekin. | Set aside. | Whisk together eggs, pumpkin, vanilla, pumpkin pie spice, and remaining 1/4 tsp. | salt in large bowl. | Bring evaporated milk, whole milk, and remaining 1/2 cup sugar to a boil in medium saucepan. | Slowly whisk milk mixture into egg mixture. | Pour 1/3 cup custard into each ramekin. | Fill pan with boiling water to come two-thirds up sides of ramekins. | Place in oven, and bake 30 to 35 minutes, until just set. | (Custards will still jiggle slightly in center.) | Remove pan from oven, and let ramekins stand in water bath 10 minutes, or until centers are completely set. | Remove ramekins from water bath with tongs, and cool on wire rack. | Cover with foil, and chill 1 hour, or up to 1 day. | To serve, run knife around custards in ramekins and invert onto individual serving plates.

# 🛑 8. Arrêt Spark

In [9]:
spark.stop()
print("✅ Spark stopped")

✅ Spark stopped